default["zabbix-server"]["dbhost"] = "localhost"
default["zabbix-server"]["dbname"] = "zabbix"
default["zabbix-server"]["dbuser"] = "zabbix"
default["zabbix-server"]["dbpassword"] = "zabbix"
default["zabbix-server"]["timeout"] = "30"
